name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  attestations: write
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "target/release/rust-sigstore-test"

      - name: List files in target/release
        run: ls -R target/release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/rust-sigstore-test
            target/release/rust-sigstore-test.intoto.jsonl
