name: release

on:
  push:
    branches:
      - main

permissions:
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "target/release/rust-sigstore-test"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-sigstore-test
          path: |
            target/release/rust-sigstore-test
            target/release/rust-sigstore-test.intoto.jsonl
