name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  attestations: write
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Generate artifact attestation
        id: attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "target/release/rust-sigstore-test"

      - name: Calculate SHA256
        id: sha256
        run: echo "sha256=$(sha256sum target/release/rust-sigstore-test | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/rust-sigstore-test
          body: |
            ## Digest (SHA256)
            `${{ steps.sha256.outputs.sha256 }}`

            [Verify on Sigstore](https://search.sigstore.dev/?hash=${{ steps.sha256.outputs.sha256 }})
