name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  attestations: write
  id-token: write
  contents: write
  packages: write

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rust-sigstore-test:${{ github.ref_name }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rust-sigstore-test:${{ github.ref_name }}"
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## Docker Image Digest (SHA256)

            | Image | Digest | Verification |
            |---|---|---|
            | `docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rust-sigstore-test:${{ github.ref_name }}` | `${{ steps.build-and-push.outputs.digest }}` | [Verify on Sigstore](https://search.sigstore.dev/?hash=${{ steps.build-and-push.outputs.digest }}) |
